parameters:
- name: build_config
  type: string
  default: 'release'

jobs:
- job: ios_cocoapods_packaging
    pool:
      vmImage: 'macOS-latest'

  workspace:
    clean: all
  steps:
    - template: steps/capi-appleframework-step.yml
    parameters:
      build_config: ${{ parameters.build_config }}
      framework_config_file: "tools/ci_build/github/apple/default_full_apple_framework_build_settings.json"
