parameters:
- name: ort_version
  type: string

- name: build_config
  type: string
  default: 'Release'

stages:
- stage: Build_iOS_CocoaPods_Archive
  jobs:
  - template: jobs/android-java-api-aar.yml
    parameters:
      ort_version: ${{ parameters.ort_version }}
      build_config: ${{ parameters.build_config }}
