name: "Linux CPU x64 Build"
on:
  workflow_dispatch:
  push:
    branches:
    - main
    - rel-*
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
env:
  DOTNET_INSTALL_DIR: "${{ github.workspace }}/dotnet"
jobs:
  linux_cpu_x64:
    runs-on: [ "self-hosted", "1ES.Pool=onnxruntime-genai-Ubuntu2204-AMD-CPU" ]
    steps:
      - name: Checkout OnnxRuntime GenAI repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build with CMake and GCC
        run: |
          set -e -x
          rm -rf build
          cmake --preset linux_gcc_cpu_release
          cmake --build --preset linux_gcc_cpu_release

      - name: Install the python wheel and test dependencies
        run: |
          python3 -m pip install -r test/python/requirements.txt --user
          python3 -m pip install -r test/python/requirements-cpu.txt --user
          python3 -m pip install build/cpu/wheel/onnxruntime_genai*.whl --user --no-deps

      - name: Use Dummy HuggingFace Token
        run: |
          echo "HF_TOKEN=12345" >> $GITHUB_ENV

      - name: Verify Build Artifacts
        if: always()
        continue-on-error: true
        run: |
          ls -l ${{ github.workspace }}/build/cpu

      # This will also download all the test models to the test/test_models directory
      # These models are used by the python tests as well as C#, C++ and others.
      - name: Run the python tests
        run: |
          export ORTGENAI_LOG_ORT_LIB=1
          python3 test/python/test_onnxruntime_genai.py --cwd test/python --test_models test/test_models

      - name: Build the C# API and Run the C# Tests
        run: |
          export ORTGENAI_LOG_ORT_LIB=1
          cd test/csharp
          dotnet test /p:Configuration=Release /p:NativeBuildOutputDir="../../build/cpu/" /p:OrtLibDir="../../ort/lib/"

      - name: Run tests
        run: |
          set -e -x
          export ORTGENAI_LOG_ORT_LIB=1
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$GITHUB_WORKSPACE/ort/lib
          ./build/cpu/test/unit_tests
