name: "Windows DirectML x64 Build"
on:
  workflow_dispatch:
  push:
    branches:
    - main
    - rel-*
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  AZCOPY_AUTO_LOGIN_TYPE: MSI
  AZCOPY_MSI_CLIENT_ID: 63b63039-6328-442f-954b-5a64d124e5b4
  binaryDir: 'build/directml/win-x64'


jobs:
  windows-directml-x64-build:
    runs-on: [ "self-hosted", "1ES.Pool=onnxruntime-genai-Win2022-GPU-A10" ]
    steps:
    - name: Checkout OnnxRuntime GenAI repo
      uses: actions/checkout@v4
      with:
        submodules: true

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11.x'
        architecture: 'x64'

    - name: Configure CMake
      run: |
        cmake --preset windows_x64_directml_release -DTEST_PHI2=False

    - name: Build with CMake
      run: |
        cmake --build --preset windows_x64_directml_release --parallel

    - name: Install the Python Wheel and Test Dependencies
      run: |
        python -m pip install -r test\python\requirements.txt
        python -m pip install -r test\python\requirements-directml.txt
        python -m pip install (Get-ChildItem ("$env:binaryDir\wheel\*.whl")) --no-deps

    - name: Verify Build Artifacts
      if: always()
      continue-on-error: true
      run: |
        Get-ChildItem -Path $env:GITHUB_WORKSPACE\$env:binaryDir -Recurse

    - name: Run tests
      run: |
        copy $env:GITHUB_WORKSPACE\ort\lib\* $env:GITHUB_WORKSPACE\$env:binaryDir\test\Release
        & .\$env:binaryDir\test\Release\unit_tests.exe